#ifndef __SERIAL_PACKET_SENT_CMD_IDS
#define __SERIAL_PACKET_SENT_CMD_IDS

/* THIS COMMANDS HANDLED BY OTHER PROCESSOR */
/* HANDLE THEM IN SERIAL PACKET HANDLER */

#define PRINT_BEMFS 0
#define PRINT_SPD_RPM 1
#define PRINT_PWM_VAL 2

#endif /* __SERIAL_PACKET_SENT_CMD_IDS */
