#ifndef __SERIAL_PACKET_SENT_CMD_IDS
#define __SERIAL_PACKET_SENT_CMD_IDS

/* THIS COMMANDS HANDLED BY OTHER PROCESSOR */
/* HANDLE THEM IN SERIAL PACKET HANDLER */

#define MOTOR_SET_STATE 0
#define MOTOR_SET_PWM 1
#define MOTOR_SET_DIRECTION 2

#endif /* __SERIAL_PACKET_SENT_CMD_IDS */
